In [1]:
import numpy as np

# 1. Create a 1D array of numbers from 0 to 20.


In [2]:
a = np.arange(21)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

# 2. Create a 2D array of shape 4x5 filled with ones.

In [3]:
a_one = np.ones((4,5))
a_one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# 3. Create an identity matrix of size 6.

In [4]:
a_i = np.identity(6)
a_i

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# 4. Create an array of 15 evenly spaced values between 10 and 50.

In [5]:
a_lin = np.linspace(10,50,15)
a_lin

array([10.        , 12.85714286, 15.71428571, 18.57142857, 21.42857143,
       24.28571429, 27.14285714, 30.        , 32.85714286, 35.71428571,
       38.57142857, 41.42857143, 44.28571429, 47.14285714, 50.        ])

# 5. Print the shape, size, and dtype of a given array.

In [6]:
a_2d = np.arange(0,25).reshape((5,5))
a_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [7]:
print('Shape of the array ',a_2d.shape)
print('Size of the array ',a_2d.size)
print('Dtype of array, ',a_2d.dtype)

Shape of the array  (5, 5)
Size of the array  25
Dtype of array,  int64


# 6. Convert a nested Python list into a 2D NumPy array.

In [8]:
python_list = [[1,3,4,5,6,7],[3,7,8,5,6,3]]
type(python_list)
python_list


[[1, 3, 4, 5, 6, 7], [3, 7, 8, 5, 6, 3]]

In [9]:
array = np.array(python_list)
type(array)

numpy.ndarray

In [10]:
array.ndim

2

# 7. Create a 3x3 array filled with the value 9.

In [11]:
a_nine = np.full((3,3),9)

# 8. Reshape a 1D array of 20 elements into a 4x5 matrix.

In [12]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [13]:
a_reshape = a.reshape((4,5))
a_reshape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# 9. Change the dtype of an array to float64.

In [14]:
a = np.arange(20).astype(np.float32)
a.dtype

dtype('float32')

In [15]:
a.dtype

dtype('float32')

# 10. Create an array of 10 zeros and then set the 5th element to 100.

In [16]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
a.put(4,100)
a

array([  0.,   0.,   0.,   0., 100.,   0.,   0.,   0.,   0.,   0.])

# 11. Extract every 3rd element from a 1D array.

In [18]:
a = np.arange(20)
print(a[3])

3


# 12. Reverse a 2D array along its rows.

In [19]:
a_2d = np.random.randint(10,100,25).reshape((5,5))
a_2d

array([[15, 57, 36, 71, 16],
       [42, 84, 93, 52, 67],
       [14, 10, 22, 33, 43],
       [46, 53, 34, 97, 76],
       [24, 16, 16, 35, 89]])

In [20]:
np.flip(a_2d,axis=0)

array([[24, 16, 16, 35, 89],
       [46, 53, 34, 97, 76],
       [14, 10, 22, 33, 43],
       [42, 84, 93, 52, 67],
       [15, 57, 36, 71, 16]])

# 13. Extract the last row and last column of a matrix.

In [21]:
a_2d = np.random.randint(10,300,30).reshape((6,5))
a_2d

array([[251, 127, 138, 218, 157],
       [283, 189, 110,  85, 109],
       [105,  61,  40, 123,  57],
       [ 37, 116,  52,  85, 208],
       [286, 199, 240, 229, 149],
       [259, 125,  51, 246,  18]])

In [22]:
a_2d[-1,:] #last row
a_2d[:,-1] #last column

array([157, 109,  57, 208, 149,  18])

# 14. Get all values from an array that are divisible by 3.

In [23]:
a = np.random.randint(1,2000,40)

In [24]:
a[a%3==0]

array([ 108, 1686, 1296, 1173, 1590,  228, 1530, 1533,  135,  846, 1818,
       1167, 1545,  150, 1743])

# 15. Replace all values greater than 50 in an array with 50.

In [25]:
a = np.random.randint(1,70,20)
a

array([35, 37, 52, 62, 43,  3, 21, 42, 45, 52, 18, 44, 26, 59, 58, 38, 47,
       46, 68,  7])

In [26]:
np.where(a>50,50,a)

array([35, 37, 50, 50, 43,  3, 21, 42, 45, 50, 18, 44, 26, 50, 50, 38, 47,
       46, 50,  7])

# 16. Extract a 3x3 sub-matrix from the center of a 6x6 matrix.

In [27]:
a = np.random.randint(10,100,36).reshape((6,6))
a

array([[27, 31, 31, 14, 71, 94],
       [71, 46, 51, 99, 98, 71],
       [64, 46, 67, 28, 96, 85],
       [18, 11, 53, 15, 93, 90],
       [25, 40, 28, 99, 40, 87],
       [42, 15, 75, 13, 29, 92]])

In [28]:
sub_metrix = a[2:5,1:4]
sub_metrix

array([[46, 67, 28],
       [11, 53, 15],
       [40, 28, 99]])

# 17. Find the indices of all elements equal to a given value

In [29]:
a = np.array([1,2,3,5,3,2,6,4,7,4,3,6,7,8,23,6,9,6,4,3,3,5,7,89,67,4,5,6,7])
value = int(input('Enter your number: '))
np.where(a==value)

(array([ 2,  4, 10, 19, 20]),)

# 18. Select rows of a matrix where the value in the first column is even.

In [30]:
a = np.random.randint(10,100,36).reshape((6,6))
a

array([[70, 79, 87, 45, 95, 33],
       [15, 77, 42, 80, 59, 75],
       [99, 45, 61, 10, 63, 64],
       [75, 89, 19, 93, 23, 60],
       [55, 61, 11, 78, 83, 80],
       [49, 90, 15, 28, 92, 62]])

In [31]:
a = a[a[:,0]%2==0]

In [32]:
a

array([[70, 79, 87, 45, 95, 33]])

# 19. Select rows at index positions 1, 4, and 6 from a matrix

In [33]:
a = np.random.randint(10,100,49).reshape((7,7))
a

array([[24, 85, 17, 28, 36, 64, 47],
       [44, 52, 37, 36, 46, 30, 14],
       [51, 82, 17, 57, 22, 31, 54],
       [60, 95, 56, 43, 60, 32, 21],
       [96, 55, 33, 91, 41, 51, 54],
       [63, 34, 38, 75, 60, 97, 68],
       [13, 10, 15, 49, 88, 17, 46]])

In [34]:
a[[1,4,6]]

array([[44, 52, 37, 36, 46, 30, 14],
       [96, 55, 33, 91, 41, 51, 54],
       [13, 10, 15, 49, 88, 17, 46]])

# 20. Set all values below 0 in an array to 0 and above 100 to 100.

In [35]:
a = np.random.randint(-10,200,49).reshape((7,7))
a

array([[ 28,  86, 126,  -3, 194,  79,  79],
       [ -1,  31, 170, 173,  59,  14,  27],
       [ 72,  85,  95, 128, 101, 160, 115],
       [142,  40,  24, 146, 101, 114, 152],
       [195, 123,  82,   6, 171,  80,  20],
       [ 31, 116, 126,  48, 115,   4, 163],
       [ 54,  24, 192,  52,  24, 151, 121]])

In [36]:
np.clip(a,0,100)

array([[ 28,  86, 100,   0, 100,  79,  79],
       [  0,  31, 100, 100,  59,  14,  27],
       [ 72,  85,  95, 100, 100, 100, 100],
       [100,  40,  24, 100, 100, 100, 100],
       [100, 100,  82,   6, 100,  80,  20],
       [ 31, 100, 100,  48, 100,   4, 100],
       [ 54,  24, 100,  52,  24, 100, 100]])

# 21. Flatten a 3D array of shape (2,3,4) into 1D

In [37]:
a = np.arange(0,24).reshape((2,3,4))

In [38]:
flatten_a = a.flatten()

In [39]:
flatten_a[3] = 100

In [40]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [41]:
ravel_a = np.ravel(a) 

In [42]:
ravel_a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [43]:
ravel_a[3] = 100

### Flatten make a new copy so change is flatten array does not effect original array, but ravel just make view so it impact on orginal array.

## 22. Reshape a (60,) array into (3,4,5).

In [44]:
a = np.random.randint(10,1000,(60,))

In [45]:
a = a.reshape(3,4,5)

In [46]:
a.shape

(3, 4, 5)

# 23. Stack two 1D arrays vertically and then horizontally.

In [47]:
a = np.arange(0,20)
b = np.linspace(1,100,20).astype(np.int32)

In [48]:
c = np.stack([a,b],axis=1) #for horizontal
d = np.stack([a,b],axis=0) #for vertical

In [49]:
d

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19],
       [  1,   6,  11,  16,  21,  27,  32,  37,  42,  47,  53,  58,  63,
         68,  73,  79,  84,  89,  94, 100]])

In [50]:
print(a.ndim)
print(c.ndim)

1
2


# 24. Concatenate two 2D arrays row-wise and column-wise.

In [51]:
a = np.arange(24).reshape(6,4)
b = np.random.randint(20,100,24).reshape(6,4).astype(np.int32)

In [52]:
b

array([[45, 62, 26, 96],
       [65, 51, 68, 70],
       [41, 90, 55, 84],
       [88, 77, 73, 84],
       [62, 42, 92, 43],
       [40, 23, 72, 25]], dtype=int32)

In [53]:
c = np.concatenate((a,b),axis=0) #for vertical
d = np.concatenate((a,b),axis=1) #for horizontal

In [54]:
print(a.ndim)
print(c.ndim)

2
2


In [55]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [45, 62, 26, 96],
       [65, 51, 68, 70],
       [41, 90, 55, 84],
       [88, 77, 73, 84],
       [62, 42, 92, 43],
       [40, 23, 72, 25]])

np.concatenate glues arrays together along an existing direction, keeping the total number of dimensions unchanged.

np.stack joins arrays along a brand-new direction, increasing the dimension count by one (e.g., turning 1D inputs into a 2D output).

1D Array Limitation: You cannot concatenate 1D arrays vertically because 1D arrays only have one axis—np.concatenate will simply join them end-to-end into a longer 1D array.

To Combine 1D Vertically: You must use np.stack (or np.vstack), which adds the necessary second dimension to create stacked rows in a 2D matrix.

# 25. Split an array of 20 elements into 4 equal parts.

In [56]:
a = np.arange(20)

In [57]:
a,b,c,d =np.split(a,4)

#  26. Transpose a 3x5 matrix 

In [58]:
a = np.arange(15).reshape(3,5)

In [59]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [60]:
a.T # 1 Way

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [61]:
np.transpose(a) # 2 Way

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

# 27. Convert a 1D array of shape (10,) into shape (10,1).

In [62]:
a = np.random.randint(1,199,10)

In [63]:
a = np.expand_dims(a,axis=1) # method 1

In [64]:
a.shape

(10, 1)

In [65]:
b = a.reshape(10,1) # method 2

In [66]:
b.shape

(10, 1)

# 28. Swap the first and last axis of a 3D array.

In [67]:
a = np.arange(24).reshape(2,3,4) 

In [68]:
a.shape

(2, 3, 4)

In [69]:
b = a.reshape(4,3,2) #method 1
c = np.swapaxes(a,0,2) #method 2
d = np.transpose(a,(2,1,0)) #method 3

In [70]:
d.shape

(4, 3, 2)

There is three method fot this task .. method 2 and 3 is actual answer

# 30. Repeat a 1D array 4 times to build a 2D array.

In [71]:
a = np.arange(5)

In [72]:
a_1 = np.tile(a,(4,1)) #method 1
b = np.broadcast_to(a,(4,len(a))) #method 2
c = np.vstack([a]*4) #method 3
d = np.repeat(a, 4).reshape(-1, 4) #method 4

In [73]:
d.shape

(5, 4)

In [74]:
d

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4]])

# 31. Add a 1D array to each row of a 2D array.

In [75]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [76]:
b = np.arange(10).reshape(2,5)

In [77]:
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [78]:
c = a+b

In [79]:
c

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13]])

# 32. Multiply each column of a matrix by a different value from a 1D array.

In [80]:
a = np.arange(5,8)
a_2d = np.arange(9).reshape(3,3)

In [81]:
print(a)
print(a_2d)

[5 6 7]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [82]:
c = a*a_2d

In [83]:
c

array([[ 0,  6, 14],
       [15, 24, 35],
       [30, 42, 56]])

# 33. Subtract the mean of each column from that column, across a whole matrix.

In [84]:
a = np.random.randint(3,100,9).reshape(3,3)

In [85]:
a

array([[49,  9, 43],
       [94, 41,  3],
       [14, 15, 62]])

In [86]:
a.mean(axis=0)  

array([52.33333333, 21.66666667, 36.        ])

In [87]:
a/a.mean(axis=0)

array([[0.93630573, 0.41538462, 1.19444444],
       [1.79617834, 1.89230769, 0.08333333],
       [0.26751592, 0.69230769, 1.72222222]])

# 34. Compute the distance between every point in array A and every point in array B

In [88]:
a = np.random.randint(20,80,10)
b = np.random.randint(1,50,10)


In [89]:
print(a)
print(b)

[28 71 21 35 42 55 47 36 60 62]
[15 45  5 14 13  3 19 48 46 16]


In [90]:
c = a-b

In [91]:
c

array([ 13,  26,  16,  21,  29,  52,  28, -12,  14,  46])

# 35. Write a function that returns 1/(1+e^-x) for an input array.

In [92]:
def sigmoid(arr):
    return 1/(1+np.exp(-arr))

In [93]:
a = np.arange(34,55)
a

array([34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54])

In [94]:
b = sigmoid(a)

In [95]:
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1.])

# 36. Write a function that converts a batch of raw scores into probabilities that sum to 1 per row. 

In [96]:
def softmax(batch_score):
    shifted_row = batch_score - np.max(batch_score, axis=1,keepdims=True)
    exp_value = np.exp(shifted_row)
    return exp_value/np.sum(exp_value,axis=1,keepdims=True)

In [97]:
import numpy as np

a = np.random.uniform(-2.0, 2.0, size=(5, 5))
print(a)
result = softmax(a)

print(np.round(result, 3))
print(np.sum(result,axis=1))

[[-1.98162426  1.92021834 -0.54787716 -0.73682478 -0.83973353]
 [ 0.25529466 -1.2104272  -0.3674424  -1.73732764  1.95894537]
 [ 1.88203261  1.04121432 -0.58016828  0.67914154 -1.22220617]
 [-1.44102516 -0.63361881  1.98986556 -1.17806819  0.70798594]
 [ 0.21021467  0.73358315 -1.83849452 -0.54838248 -1.861405  ]]
[[0.016 0.807 0.068 0.057 0.051]
 [0.135 0.031 0.073 0.018 0.743]
 [0.537 0.232 0.046 0.161 0.024]
 [0.023 0.051 0.702 0.03  0.195]
 [0.293 0.495 0.038 0.137 0.037]]
[1. 1. 1. 1. 1.]


# 37. Write a function that zeroes out all negative numbers in an array.

In [98]:
def negative_zero(array):
    return np.where(array<0,0,array)
    # or
    # np.clip(array,0,None)


In [99]:
a = np.array([1,-2,3])

In [100]:
negative_zero(a)

array([1, 0, 3])

# 38. Compute the elementwise min and max of two arrays.

In [101]:
a = np.arange(0,25).reshape(5,5)
b = np.random.randint(0,35,25).reshape(5,5)

In [102]:
print(a)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 1 32 22 15 29]
 [28 28 13 29 22]
 [11 15 23 12 32]
 [34  7 25 20  7]
 [ 1 30 16  9 14]]


In [103]:
np.maximum(a,b)
np.minimum(a,b)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 12, 14],
       [15,  7, 17, 18,  7],
       [ 1, 21, 16,  9, 14]])

# 39. Convert an integer array of class labels into a one-hot encoded 2D array.

# 41. Compute mean, median, std and variance of every column in a matrix.

In [106]:
a = np.random.randint(0,199,25).reshape(5,5)

In [107]:
a

array([[109,  46, 187, 131, 182],
       [ 78,  95,   3, 100,  70],
       [ 67, 107, 172, 109,  60],
       [ 11, 120, 104,  13,   1],
       [133,  53, 123, 118, 142]])

In [110]:
mean = np.mean(a,axis=0)
median = np.median(a,axis=0)
std = np.std(a,axis=0)
variance = np.var(a,axis=0)

In [111]:
print(f'The mean is {mean} \nThe median is {median} \nThe std is {std}\nThe variance is {variance}')

The mean is [ 79.6  84.2 117.8  94.2  91. ] 
The median is [ 78.  95. 123. 109.  70.] 
The std is [41.43235451 29.49847454 64.9966153  41.87314175 63.84982381]
The variance is [1716.64  870.16 4224.56 1753.36 4076.8 ]


# 42. Find the minimum and maximum value of every column in a matrix.

In [112]:
a = np.random.uniform(1,14,15).reshape(5,3)

In [113]:
a

array([[ 3.19115006,  9.35271128,  1.07692676],
       [12.83797659,  7.67488458, 10.25988285],
       [ 2.17717131,  9.62288217, 10.25310868],
       [ 9.48238352,  8.5829697 ,  1.94889507],
       [ 9.26577296,  8.36216544,  4.9239955 ]])

In [116]:
max_number = np.max(a,axis=0)
min_number = np.min(a,axis = 0)

In [119]:
print(f'The maximum number is {max_number}\nThe minimum number is {min_number}')

The maximum number is [12.83797659  9.62288217 10.25988285]
The minimum number is [2.17717131 7.67488458 1.07692676]
