In [2]:
import numpy as np

# 1. Create a 1D array of numbers from 0 to 20.


In [3]:
a = np.arange(21)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

# 2. Create a 2D array of shape 4x5 filled with ones.

In [4]:
a_one = np.ones((4,5))
a_one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# 3. Create an identity matrix of size 6.

In [5]:
a_i = np.identity(6)
a_i

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# 4. Create an array of 15 evenly spaced values between 10 and 50.

In [6]:
a_lin = np.linspace(10,50,15)
a_lin

array([10.        , 12.85714286, 15.71428571, 18.57142857, 21.42857143,
       24.28571429, 27.14285714, 30.        , 32.85714286, 35.71428571,
       38.57142857, 41.42857143, 44.28571429, 47.14285714, 50.        ])

# 5. Print the shape, size, and dtype of a given array.

In [7]:
a_2d = np.arange(0,25).reshape((5,5))
a_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [8]:
print('Shape of the array ',a_2d.shape)
print('Size of the array ',a_2d.size)
print('Dtype of array, ',a_2d.dtype)

Shape of the array  (5, 5)
Size of the array  25
Dtype of array,  int64


# 6. Convert a nested Python list into a 2D NumPy array.

In [9]:
python_list = [[1,3,4,5,6,7],[3,7,8,5,6,3]]
type(python_list)
python_list


[[1, 3, 4, 5, 6, 7], [3, 7, 8, 5, 6, 3]]

In [10]:
array = np.array(python_list)
type(array)

numpy.ndarray

In [11]:
array.ndim

2

# 7. Create a 3x3 array filled with the value 9.

In [12]:
a_nine = np.full((3,3),9)

# 8. Reshape a 1D array of 20 elements into a 4x5 matrix.

In [13]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
a_reshape = a.reshape((4,5))
a_reshape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# 9. Change the dtype of an array to float64.

In [15]:
a = np.arange(20).astype(np.float32)
a.dtype

dtype('float32')

In [16]:
a.dtype

dtype('float32')

# 10. Create an array of 10 zeros and then set the 5th element to 100.

In [17]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
a.put(4,100)
a

array([  0.,   0.,   0.,   0., 100.,   0.,   0.,   0.,   0.,   0.])

# 11. Extract every 3rd element from a 1D array.

In [19]:
a = np.arange(20)
print(a[3])

3


# 12. Reverse a 2D array along its rows.

In [20]:
a_2d = np.random.randint(10,100,25).reshape((5,5))
a_2d

array([[86, 92, 50, 17, 27],
       [46, 62, 54, 54, 79],
       [36, 29, 67, 82, 99],
       [62, 48, 44, 42, 18],
       [80, 59, 59, 48, 94]])

In [21]:
np.flip(a_2d,axis=0)

array([[80, 59, 59, 48, 94],
       [62, 48, 44, 42, 18],
       [36, 29, 67, 82, 99],
       [46, 62, 54, 54, 79],
       [86, 92, 50, 17, 27]])

# 13. Extract the last row and last column of a matrix.

In [22]:
a_2d = np.random.randint(10,300,30).reshape((6,5))
a_2d

array([[ 62, 134, 214, 276, 298],
       [ 49,  36, 103, 121, 154],
       [270, 289,  33, 253, 115],
       [123,  99, 199,  72, 165],
       [270, 201, 121, 278,  97],
       [223,  96,  60, 191, 242]])

In [23]:
a_2d[-1,:] #last row
a_2d[:,-1] #last column

array([298, 154, 115, 165,  97, 242])

# 14. Get all values from an array that are divisible by 3.

In [24]:
a = np.random.randint(1,2000,40)

In [25]:
a[a%3==0]

array([1251, 1221,  876,  261,  390, 1140, 1311,  759,    9])

# 15. Replace all values greater than 50 in an array with 50.

In [26]:
a = np.random.randint(1,70,20)
a

array([40,  2, 39, 61, 54, 10, 24, 66, 57, 31, 28, 44, 57, 36, 55, 52, 29,
       16, 48, 62])

In [27]:
np.where(a>50,50,a)

array([40,  2, 39, 50, 50, 10, 24, 50, 50, 31, 28, 44, 50, 36, 50, 50, 29,
       16, 48, 50])

# 16. Extract a 3x3 sub-matrix from the center of a 6x6 matrix.

In [28]:
a = np.random.randint(10,100,36).reshape((6,6))
a

array([[17, 54, 65, 52, 57, 29],
       [28, 42, 39, 51, 85, 96],
       [65, 56, 36, 72, 36, 63],
       [93, 39, 10, 43, 42, 17],
       [97, 90, 77, 12, 45, 72],
       [10, 72, 52, 74, 67, 13]])

In [29]:
sub_metrix = a[2:5,1:4]
sub_metrix

array([[56, 36, 72],
       [39, 10, 43],
       [90, 77, 12]])

# 17. Find the indices of all elements equal to a given value

In [30]:
a = np.array([1,2,3,5,3,2,6,4,7,4,3,6,7,8,23,6,9,6,4,3,3,5,7,89,67,4,5,6,7])
value = int(input('Enter your number: '))
np.where(a==value)

(array([ 2,  4, 10, 19, 20]),)

# 18. Select rows of a matrix where the value in the first column is even.

In [31]:
a = np.random.randint(10,100,36).reshape((6,6))
a

array([[97, 48, 21, 53, 38, 85],
       [11, 38, 26, 82, 57, 99],
       [51, 80, 33, 30, 51, 18],
       [22, 81, 29, 97, 18, 80],
       [80, 64, 55, 36, 67, 61],
       [11, 18, 24, 80, 13, 60]])

In [32]:
a = a[a[:,0]%2==0]

In [33]:
a

array([[22, 81, 29, 97, 18, 80],
       [80, 64, 55, 36, 67, 61]])

# 19. Select rows at index positions 1, 4, and 6 from a matrix

In [34]:
a = np.random.randint(10,100,49).reshape((7,7))
a

array([[24, 48, 64, 68, 85, 79, 27],
       [93, 26, 47, 82, 42, 77, 82],
       [82, 20, 73, 84, 32, 95, 70],
       [63, 19, 11, 63, 56, 57, 76],
       [95, 28, 92, 74, 80, 69, 60],
       [99, 22, 95, 44, 65, 46, 94],
       [84, 40, 41, 40, 94, 71, 68]])

In [35]:
a[[1,4,6]]

array([[93, 26, 47, 82, 42, 77, 82],
       [95, 28, 92, 74, 80, 69, 60],
       [84, 40, 41, 40, 94, 71, 68]])

# 20. Set all values below 0 in an array to 0 and above 100 to 100.

In [36]:
a = np.random.randint(-10,200,49).reshape((7,7))
a

array([[131, 151, 189, 166, 182,  71, 127],
       [ 58, 197,  77, -10, 189, 121, 134],
       [ 71,  13,  46, 128, 117, 153, 159],
       [ 55,  19, 167,  75,  -7,  87,  37],
       [ 31, 103,  92,  52, 122,  60,  56],
       [ 33,  -6,  83,  77, 147,  77,  93],
       [ 74,  39,  43, 118, 110,  79, 133]])

In [37]:
np.clip(a,0,100)

array([[100, 100, 100, 100, 100,  71, 100],
       [ 58, 100,  77,   0, 100, 100, 100],
       [ 71,  13,  46, 100, 100, 100, 100],
       [ 55,  19, 100,  75,   0,  87,  37],
       [ 31, 100,  92,  52, 100,  60,  56],
       [ 33,   0,  83,  77, 100,  77,  93],
       [ 74,  39,  43, 100, 100,  79, 100]])

# 21. Flatten a 3D array of shape (2,3,4) into 1D

In [38]:
a = np.arange(0,24).reshape((2,3,4))

In [39]:
flatten_a = a.flatten()

In [40]:
flatten_a[3] = 100

In [41]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [42]:
ravel_a = np.ravel(a) 

In [43]:
ravel_a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [44]:
ravel_a[3] = 100

### Flatten make a new copy so change is flatten array does not effect original array, but ravel just make view so it impact on orginal array.

## 22. Reshape a (60,) array into (3,4,5).

In [45]:
a = np.random.randint(10,1000,(60,))

In [46]:
a = a.reshape(3,4,5)

In [47]:
a.shape

(3, 4, 5)

# 23. Stack two 1D arrays vertically and then horizontally.

In [48]:
a = np.arange(0,20)
b = np.linspace(1,100,20).astype(np.int32)

In [49]:
c = np.stack([a,b],axis=1) #for horizontal
d = np.stack([a,b],axis=0) #for vertical

In [50]:
d

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19],
       [  1,   6,  11,  16,  21,  27,  32,  37,  42,  47,  53,  58,  63,
         68,  73,  79,  84,  89,  94, 100]])

In [51]:
print(a.ndim)
print(c.ndim)

1
2


# 24. Concatenate two 2D arrays row-wise and column-wise.

In [52]:
a = np.arange(24).reshape(6,4)
b = np.random.randint(20,100,24).reshape(6,4).astype(np.int32)

In [53]:
b

array([[28, 69, 51, 37],
       [66, 70, 33, 80],
       [93, 92, 98, 45],
       [58, 42, 91, 57],
       [93, 44, 72, 85],
       [78, 90, 52, 61]], dtype=int32)

In [54]:
c = np.concatenate((a,b),axis=0) #for vertical
d = np.concatenate((a,b),axis=1) #for horizontal

In [55]:
print(a.ndim)
print(c.ndim)

2
2


In [56]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [28, 69, 51, 37],
       [66, 70, 33, 80],
       [93, 92, 98, 45],
       [58, 42, 91, 57],
       [93, 44, 72, 85],
       [78, 90, 52, 61]])

np.concatenate glues arrays together along an existing direction, keeping the total number of dimensions unchanged.

np.stack joins arrays along a brand-new direction, increasing the dimension count by one (e.g., turning 1D inputs into a 2D output).

1D Array Limitation: You cannot concatenate 1D arrays vertically because 1D arrays only have one axis—np.concatenate will simply join them end-to-end into a longer 1D array.

To Combine 1D Vertically: You must use np.stack (or np.vstack), which adds the necessary second dimension to create stacked rows in a 2D matrix.

# 25. Split an array of 20 elements into 4 equal parts.

In [58]:
a = np.arange(20)

In [61]:
a,b,c,d =np.split(a,4)

#  26. Transpose a 3x5 matrix 

In [66]:
a = np.arange(15).reshape(3,5)

In [67]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
a.T # 1 Way

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [ ]:
np.transpose(a) # 2 Way

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

# 27. Convert a 1D array of shape (10,) into shape (10,1).

In [70]:
a = np.random.randint(1,199,10)

In [ ]:
a.

(10,)