In [3]:
import numpy as np

# 1. Create a 1D array of numbers from 0 to 20.


In [4]:
a = np.arange(21)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

# 2. Create a 2D array of shape 4x5 filled with ones.

In [7]:
a_one = np.ones((4,5))
a_one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# 3. Create an identity matrix of size 6.

In [9]:
a_i = np.identity(6)
a_i

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# 4. Create an array of 15 evenly spaced values between 10 and 50.

In [14]:
a_lin = np.linspace(10,50,15)
a_lin

array([10.        , 12.85714286, 15.71428571, 18.57142857, 21.42857143,
       24.28571429, 27.14285714, 30.        , 32.85714286, 35.71428571,
       38.57142857, 41.42857143, 44.28571429, 47.14285714, 50.        ])

# 5. Print the shape, size, and dtype of a given array.

In [17]:
a_2d = np.arange(0,25).reshape((5,5))
a_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
print('Shape of the array ',a_2d.shape)
print('Size of the array ',a_2d.size)
print('Dtype of array, ',a_2d.dtype)

Shape of the array  (5, 5)
Size of the array  25
Dtype of array,  int64


# 6. Convert a nested Python list into a 2D NumPy array.

In [38]:
python_list = [[1,3,4,5,6,7],[3,7,8,5,6,3]]
type(python_list)
python_list


[[1, 3, 4, 5, 6, 7], [3, 7, 8, 5, 6, 3]]

In [39]:
array = np.array(python_list)
type(array)

numpy.ndarray

In [43]:
array.ndim

2

# 7. Create a 3x3 array filled with the value 9.

In [28]:
a_nine = np.full((3,3),9)

# 8. Reshape a 1D array of 20 elements into a 4x5 matrix.

In [32]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [34]:
a_reshape = a.reshape((4,5))
a_reshape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# 9. Change the dtype of an array to float64.

In [55]:
a = np.arange(20).astype(np.float32)
a.dtype

dtype('float32')

In [57]:
a.dtype

dtype('float32')

# 10. Create an array of 10 zeros and then set the 5th element to 100.

In [64]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [65]:
a.put(4,100)
a

array([  0.,   0.,   0.,   0., 100.,   0.,   0.,   0.,   0.,   0.])

# 11. Extract every 3rd element from a 1D array.

In [71]:
a = np.arange(20)
print(a[3])

3


# 12. Reverse a 2D array along its rows.

In [79]:
a_2d = np.random.randint(10,100,25).reshape((5,5))
a_2d

array([[23, 51, 30, 98, 72],
       [65, 98, 53, 64, 74],
       [24, 26, 59, 61, 81],
       [10, 72, 23, 81, 65],
       [18, 30, 55, 53, 94]])

In [81]:
np.flip(a_2d,axis=0)

array([[18, 30, 55, 53, 94],
       [10, 72, 23, 81, 65],
       [24, 26, 59, 61, 81],
       [65, 98, 53, 64, 74],
       [23, 51, 30, 98, 72]])

# 13. Extract the last row and last column of a matrix.

In [7]:
a_2d = np.random.randint(10,300,30).reshape((6,5))
a_2d

array([[140,  62, 105, 256, 205],
       [116, 195,  73,  45,  99],
       [140, 155, 128,  40, 232],
       [250, 117, 263,  39, 254],
       [266, 190, 187,  18,  70],
       [ 35,  30, 101, 140, 289]])

In [12]:
a_2d[-1,:] #last row
a_2d[:,-1] #last column

array([205,  99, 232, 254,  70, 289])

# 14. Get all values from an array that are divisible by 3.

In [ ]:
a = np.random.randint(1,2000,40)

In [14]:
a[a%3==0]

array([ 267,  465,  123, 1689,  804,  153,   18,  195, 1926,  570,  363])

# 15. Replace all values greater than 50 in an array with 50.

In [16]:
a = np.random.randint(1,70,20)
a

array([12, 21, 65, 25, 37,  8,  3, 34, 20, 41, 57, 50, 15, 40, 62,  2, 55,
        4, 22, 62])

In [17]:
np.where(a>50,50,a)

array([12, 21, 50, 25, 37,  8,  3, 34, 20, 41, 50, 50, 15, 40, 50,  2, 50,
        4, 22, 50])

# 16. Extract a 3x3 sub-matrix from the center of a 6x6 matrix.

In [25]:
a = np.random.randint(10,100,36).reshape((6,6))
a

array([[54, 57, 10, 81, 39, 60],
       [37, 58, 72, 27, 67, 17],
       [93, 10, 97, 17, 70, 39],
       [11, 63, 72, 75, 39, 60],
       [21, 83, 12, 57, 72, 78],
       [23, 37, 82, 93, 59, 65]])

In [27]:
sub_metrix = a[2:5,1:4]
sub_metrix

array([[10, 97, 17],
       [63, 72, 75],
       [83, 12, 57]])

# 17. Find the indices of all elements equal to a given value

In [31]:
a = np.array([1,2,3,5,3,2,6,4,7,4,3,6,7,8,23,6,9,6,4,3,3,5,7,89,67,4,5,6,7])
value = int(input('Enter your number: '))
np.where(a==value)

(array([ 7,  9, 18, 25]),)

# 18. Select rows of a matrix where the value in the first column is even.

In [32]:
a = np.random.randint(10,100,36).reshape((6,6))
a

array([[74, 99, 53, 41, 40, 81],
       [44, 53, 21, 88, 10, 15],
       [76, 92, 29, 95, 32, 90],
       [96, 44, 45, 46, 65, 86],
       [83, 25, 83, 64, 73, 92],
       [93, 11, 95, 35, 94, 37]])

In [33]:
a = a[a[:,0]%2==0]

In [34]:
a

array([[74, 99, 53, 41, 40, 81],
       [44, 53, 21, 88, 10, 15],
       [76, 92, 29, 95, 32, 90],
       [96, 44, 45, 46, 65, 86]])

# 19. Select rows at index positions 1, 4, and 6 from a matrix

In [39]:
a = np.random.randint(10,100,49).reshape((7,7))
a

array([[61, 89, 99, 93, 40, 54, 57],
       [88, 26, 30, 92, 94, 52, 52],
       [57, 71, 95, 94, 34, 46, 22],
       [86, 27, 52, 44, 61, 96, 76],
       [68, 88, 49, 54, 26, 53, 94],
       [56, 87, 15, 70, 22, 64, 32],
       [34, 32, 10, 78, 11, 22, 92]])

In [41]:
a[[1,4,6]]

array([[88, 26, 30, 92, 94, 52, 52],
       [68, 88, 49, 54, 26, 53, 94],
       [34, 32, 10, 78, 11, 22, 92]])

# 20. Set all values below 0 in an array to 0 and above 100 to 100.

In [44]:
a = np.random.randint(-10,200,49).reshape((7,7))
a

array([[ 70,  25,  18,  -7, 109,  54,  64],
       [ 30, 186,  72, 180,  84, 178,  21],
       [ 48,  26,  -6, 177, 140, 104,  46],
       [ 44,  93, 156,  84, 161,  46,  99],
       [ 99, 162, 132,  25,  18,   8, 108],
       [127,  62,  82,  -3, 172,  31, 127],
       [154,  73, 118,   3,  -3, 173,  87]])

In [45]:
np.clip(a,0,100)

array([[ 70,  25,  18,   0, 100,  54,  64],
       [ 30, 100,  72, 100,  84, 100,  21],
       [ 48,  26,   0, 100, 100, 100,  46],
       [ 44,  93, 100,  84, 100,  46,  99],
       [ 99, 100, 100,  25,  18,   8, 100],
       [100,  62,  82,   0, 100,  31, 100],
       [100,  73, 100,   3,   0, 100,  87]])