In [1]:
import numpy as np

# 1. Create a 1D array of numbers from 0 to 20.


In [2]:
a = np.arange(21)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

# 2. Create a 2D array of shape 4x5 filled with ones.

In [3]:
a_one = np.ones((4,5))
a_one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# 3. Create an identity matrix of size 6.

In [4]:
a_i = np.identity(6)
a_i

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# 4. Create an array of 15 evenly spaced values between 10 and 50.

In [5]:
a_lin = np.linspace(10,50,15)
a_lin

array([10.        , 12.85714286, 15.71428571, 18.57142857, 21.42857143,
       24.28571429, 27.14285714, 30.        , 32.85714286, 35.71428571,
       38.57142857, 41.42857143, 44.28571429, 47.14285714, 50.        ])

# 5. Print the shape, size, and dtype of a given array.

In [6]:
a_2d = np.arange(0,25).reshape((5,5))
a_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [7]:
print('Shape of the array ',a_2d.shape)
print('Size of the array ',a_2d.size)
print('Dtype of array, ',a_2d.dtype)

Shape of the array  (5, 5)
Size of the array  25
Dtype of array,  int64


# 6. Convert a nested Python list into a 2D NumPy array.

In [8]:
python_list = [[1,3,4,5,6,7],[3,7,8,5,6,3]]
type(python_list)
python_list


[[1, 3, 4, 5, 6, 7], [3, 7, 8, 5, 6, 3]]

In [9]:
array = np.array(python_list)
type(array)

numpy.ndarray

In [10]:
array.ndim

2

# 7. Create a 3x3 array filled with the value 9.

In [11]:
a_nine = np.full((3,3),9)

# 8. Reshape a 1D array of 20 elements into a 4x5 matrix.

In [12]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [13]:
a_reshape = a.reshape((4,5))
a_reshape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# 9. Change the dtype of an array to float64.

In [14]:
a = np.arange(20).astype(np.float32)
a.dtype

dtype('float32')

In [15]:
a.dtype

dtype('float32')

# 10. Create an array of 10 zeros and then set the 5th element to 100.

In [16]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
a.put(4,100)
a

array([  0.,   0.,   0.,   0., 100.,   0.,   0.,   0.,   0.,   0.])

# 11. Extract every 3rd element from a 1D array.

In [18]:
a = np.arange(20)
print(a[3])

3


# 12. Reverse a 2D array along its rows.

In [19]:
a_2d = np.random.randint(10,100,25).reshape((5,5))
a_2d

array([[36, 96, 28, 71, 77],
       [75, 36, 95, 59, 45],
       [56, 55, 44, 89, 20],
       [72, 17, 99, 87, 93],
       [54, 19, 65, 55, 63]])

In [20]:
np.flip(a_2d,axis=0)

array([[54, 19, 65, 55, 63],
       [72, 17, 99, 87, 93],
       [56, 55, 44, 89, 20],
       [75, 36, 95, 59, 45],
       [36, 96, 28, 71, 77]])

# 13. Extract the last row and last column of a matrix.

In [21]:
a_2d = np.random.randint(10,300,30).reshape((6,5))
a_2d

array([[123, 137,  32,  89, 292],
       [ 68, 176, 268, 178, 137],
       [230, 240, 221, 235, 281],
       [ 75, 106, 288, 193, 133],
       [119, 222, 100,  86,  17],
       [243, 133, 252,  98, 107]])

In [22]:
a_2d[-1,:] #last row
a_2d[:,-1] #last column

array([292, 137, 281, 133,  17, 107])

# 14. Get all values from an array that are divisible by 3.

In [23]:
a = np.random.randint(1,2000,40)

In [24]:
a[a%3==0]

array([1422, 1341, 1884,   33, 1329, 1323,  645, 1617,  192, 1647,   63,
        957, 1806, 1530,   63, 1542])

# 15. Replace all values greater than 50 in an array with 50.

In [25]:
a = np.random.randint(1,70,20)
a

array([61, 57, 43, 59, 22, 57, 37, 62, 26, 43,  1, 53, 16, 21, 53, 68, 41,
       20, 66,  1])

In [26]:
np.where(a>50,50,a)

array([50, 50, 43, 50, 22, 50, 37, 50, 26, 43,  1, 50, 16, 21, 50, 50, 41,
       20, 50,  1])

# 16. Extract a 3x3 sub-matrix from the center of a 6x6 matrix.

In [27]:
a = np.random.randint(10,100,36).reshape((6,6))
a

array([[25, 57, 88, 27, 59, 16],
       [74, 32, 94, 60, 38, 30],
       [91, 45, 56, 20, 27, 17],
       [60, 74, 53, 51, 76, 88],
       [82, 54, 31, 53, 65, 60],
       [51, 37, 66, 83, 23, 67]])

In [28]:
sub_metrix = a[2:5,1:4]
sub_metrix

array([[45, 56, 20],
       [74, 53, 51],
       [54, 31, 53]])

# 17. Find the indices of all elements equal to a given value

In [29]:
a = np.array([1,2,3,5,3,2,6,4,7,4,3,6,7,8,23,6,9,6,4,3,3,5,7,89,67,4,5,6,7])
value = int(input('Enter your number: '))
np.where(a==value)

(array([], dtype=int64),)

# 18. Select rows of a matrix where the value in the first column is even.

In [30]:
a = np.random.randint(10,100,36).reshape((6,6))
a

array([[13, 47, 89, 15, 70, 52],
       [64, 89, 44, 58, 25, 30],
       [68, 77, 66, 33, 76, 79],
       [24, 87, 56, 84, 55, 72],
       [98, 33, 37, 81, 82, 95],
       [59, 24, 73, 90, 76, 58]])

In [31]:
a = a[a[:,0]%2==0]

In [32]:
a

array([[64, 89, 44, 58, 25, 30],
       [68, 77, 66, 33, 76, 79],
       [24, 87, 56, 84, 55, 72],
       [98, 33, 37, 81, 82, 95]])

# 19. Select rows at index positions 1, 4, and 6 from a matrix

In [33]:
a = np.random.randint(10,100,49).reshape((7,7))
a

array([[63, 33, 23, 31, 25, 95, 94],
       [39, 33, 74, 67, 42, 77, 86],
       [15, 32, 70, 59, 98, 89, 99],
       [94, 52, 53, 63, 30, 11, 25],
       [98, 38, 20, 19, 89, 83, 63],
       [12, 15, 59, 87, 78, 23, 14],
       [94, 31, 59, 11, 20, 32, 41]])

In [34]:
a[[1,4,6]]

array([[39, 33, 74, 67, 42, 77, 86],
       [98, 38, 20, 19, 89, 83, 63],
       [94, 31, 59, 11, 20, 32, 41]])

# 20. Set all values below 0 in an array to 0 and above 100 to 100.

In [35]:
a = np.random.randint(-10,200,49).reshape((7,7))
a

array([[ 65,  51, 126,  82,  69, 101,  -8],
       [ 94,  55,  76,  12, 127,  33,  37],
       [120, 116, 141,  20,  35,  42,  -5],
       [190,  63, 126,  67, 118,  59, 133],
       [171,  -1, 144,   1,  19, 191, 143],
       [127,  24,  78,  18,  94,  45,  51],
       [142, 169,  49, 122,  17, 166, 162]])

In [36]:
np.clip(a,0,100)

array([[ 65,  51, 100,  82,  69, 100,   0],
       [ 94,  55,  76,  12, 100,  33,  37],
       [100, 100, 100,  20,  35,  42,   0],
       [100,  63, 100,  67, 100,  59, 100],
       [100,   0, 100,   1,  19, 100, 100],
       [100,  24,  78,  18,  94,  45,  51],
       [100, 100,  49, 100,  17, 100, 100]])

# 21. Flatten a 3D array of shape (2,3,4) into 1D

In [37]:
a = np.arange(0,24).reshape((2,3,4))

In [38]:
flatten_a = a.flatten()

In [39]:
flatten_a[3] = 100

In [40]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [41]:
ravel_a = np.ravel(a) 

In [42]:
ravel_a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [43]:
ravel_a[3] = 100

### Flatten make a new copy so change is flatten array does not effect original array, but ravel just make view so it impact on orginal array.

## 22. Reshape a (60,) array into (3,4,5).

In [44]:
a = np.random.randint(10,1000,(60,))

In [45]:
a = a.reshape(3,4,5)

In [46]:
a.shape

(3, 4, 5)

# 23. Stack two 1D arrays vertically and then horizontally.

In [47]:
a = np.arange(0,20)
b = np.linspace(1,100,20).astype(np.int32)

In [48]:
c = np.stack([a,b],axis=1) #for horizontal
d = np.stack([a,b],axis=0) #for vertical

In [49]:
d

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19],
       [  1,   6,  11,  16,  21,  27,  32,  37,  42,  47,  53,  58,  63,
         68,  73,  79,  84,  89,  94, 100]])

In [50]:
print(a.ndim)
print(c.ndim)

1
2


# 24. Concatenate two 2D arrays row-wise and column-wise.

In [51]:
a = np.arange(24).reshape(6,4)
b = np.random.randint(20,100,24).reshape(6,4).astype(np.int32)

In [52]:
b

array([[82, 78, 65, 60],
       [32, 27, 73, 61],
       [96, 60, 82, 80],
       [75, 46, 85, 32],
       [89, 46, 64, 70],
       [89, 84, 59, 91]], dtype=int32)

In [53]:
c = np.concatenate((a,b),axis=0) #for vertical
d = np.concatenate((a,b),axis=1) #for horizontal

In [54]:
print(a.ndim)
print(c.ndim)

2
2


In [55]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [82, 78, 65, 60],
       [32, 27, 73, 61],
       [96, 60, 82, 80],
       [75, 46, 85, 32],
       [89, 46, 64, 70],
       [89, 84, 59, 91]])

np.concatenate glues arrays together along an existing direction, keeping the total number of dimensions unchanged.

np.stack joins arrays along a brand-new direction, increasing the dimension count by one (e.g., turning 1D inputs into a 2D output).

1D Array Limitation: You cannot concatenate 1D arrays vertically because 1D arrays only have one axis—np.concatenate will simply join them end-to-end into a longer 1D array.

To Combine 1D Vertically: You must use np.stack (or np.vstack), which adds the necessary second dimension to create stacked rows in a 2D matrix.

# 25. Split an array of 20 elements into 4 equal parts.

In [56]:
a = np.arange(20)

In [57]:
a,b,c,d =np.split(a,4)

#  26. Transpose a 3x5 matrix 

In [58]:
a = np.arange(15).reshape(3,5)

In [59]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [60]:
a.T # 1 Way

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [61]:
np.transpose(a) # 2 Way

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

# 27. Convert a 1D array of shape (10,) into shape (10,1).

In [62]:
a = np.random.randint(1,199,10)

In [63]:
a = np.expand_dims(a,axis=1) # method 1

In [64]:
a.shape

(10, 1)

In [65]:
b = a.reshape(10,1) # method 2

In [66]:
b.shape

(10, 1)

# 28. Swap the first and last axis of a 3D array.

In [67]:
a = np.arange(24).reshape(2,3,4) 

In [68]:
a.shape

(2, 3, 4)

In [69]:
b = a.reshape(4,3,2) #method 1
c = np.swapaxes(a,0,2) #method 2
d = np.transpose(a,(2,1,0)) #method 3

In [70]:
d.shape

(4, 3, 2)

There is three method fot this task .. method 2 and 3 is actual answer

# 30. Repeat a 1D array 4 times to build a 2D array.

In [71]:
a = np.arange(5)

In [72]:
a_1 = np.tile(a,(4,1)) #method 1
b = np.broadcast_to(a,(4,len(a))) #method 2
c = np.vstack([a]*4) #method 3
d = np.repeat(a, 4).reshape(-1, 4) #method 4

In [73]:
d.shape

(5, 4)

In [74]:
d

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4]])

# 31. Add a 1D array to each row of a 2D array.

In [75]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [76]:
b = np.arange(10).reshape(2,5)

In [77]:
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [78]:
c = a+b

In [79]:
c

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13]])

# 32. Multiply each column of a matrix by a different value from a 1D array.

In [80]:
a = np.arange(5,8)
a_2d = np.arange(9).reshape(3,3)

In [81]:
print(a)
print(a_2d)

[5 6 7]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [82]:
c = a*a_2d

In [83]:
c

array([[ 0,  6, 14],
       [15, 24, 35],
       [30, 42, 56]])

# 33. Subtract the mean of each column from that column, across a whole matrix.

In [84]:
a = np.random.randint(3,100,9).reshape(3,3)

In [85]:
a

array([[73, 36, 25],
       [ 5, 89, 35],
       [43, 71, 19]])

In [86]:
a.mean(axis=0)  

array([40.33333333, 65.33333333, 26.33333333])

In [87]:
a/a.mean(axis=0)

array([[1.80991736, 0.55102041, 0.94936709],
       [0.12396694, 1.3622449 , 1.32911392],
       [1.0661157 , 1.08673469, 0.72151899]])

# 34. Compute the distance between every point in array A and every point in array B

In [88]:
a = np.random.randint(20,80,10)
b = np.random.randint(1,50,10)


In [89]:
print(a)
print(b)

[20 64 45 45 72 36 45 74 30 55]
[42  1 24 20 49  4 15  3 42 36]


In [90]:
c = a-b

In [91]:
c

array([-22,  63,  21,  25,  23,  32,  30,  71, -12,  19])

# 35. Write a function that returns 1/(1+e^-x) for an input array.

In [92]:
def sigmoid(arr):
    return 1/(1+np.exp(-arr))

In [94]:
a = np.arange(34,55)
a

array([34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54])

In [96]:
b = sigmoid(a)

In [97]:
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1.])

# 36. Write a function that converts a batch of raw scores into probabilities that sum to 1 per row. 

In [113]:
def softmax(batch_score):
    shifted_row = batch_score - np.max(batch_score, axis=1,keepdims=True)
    exp_value = np.exp(shifted_row)
    return exp_value/np.sum(exp_value,axis=1,keepdims=True)

In [ ]:
import numpy as np

a = np.random.uniform(-2.0, 2.0, size=(5, 5))
print(a)
result = softmax(a)

print(np.round(result, 3))
print(np.sum(result,axis=1))

[[29.2821228  27.21834729 13.73235754 22.72850412 27.18394547]
 [22.07011499 14.37347737 18.82831201 25.53030972 28.86557359]
 [28.99729523 13.35267554 14.076309   22.9048898  11.28501178]
 [17.43518653 27.48506415 17.9690901  29.73024004 27.19393998]
 [14.04608499 19.13859781 22.07857879 22.34859848 10.86079083]]
[[0.799 0.101 0.    0.001 0.098]
 [0.001 0.    0.    0.034 0.965]
 [0.998 0.    0.    0.002 0.   ]
 [0.    0.089 0.    0.844 0.067]
 [0.    0.022 0.423 0.554 0.   ]]
[1. 1. 1. 1. 1.]


# 37. Write a function that zeroes out all negative numbers in an array.

In [151]:
def negative_zero(array):
    return np.where(array<0,0,array)
    # or
    # np.clip(array,0,None)


In [152]:
a = np.array([1,-2,3])

In [153]:
negative_zero(a)

array([1, 0, 3])

# 38. Compute the elementwise min and max of two arrays.

In [154]:
a = np.arange(0,25).reshape(5,5)
b = np.random.randint(0,35,25).reshape(5,5)

In [159]:
print(a)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[31  6  7 29 19]
 [23 15 17  8 24]
 [10  4 12 13 14]
 [21 23 31 27 30]
 [29 10 21 32 25]]


In [163]:
np.maximum(a,b)
np.minimum(a,b)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10,  4, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 10, 21, 23, 24]])

# 39. Convert an integer array of class labels into a one-hot encoded 2D array.