In [1]:
import numpy as np

# 1. Create a 1D array of numbers from 0 to 20.


In [2]:
a = np.arange(21)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

# 2. Create a 2D array of shape 4x5 filled with ones.

In [3]:
a_one = np.ones((4,5))
a_one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# 3. Create an identity matrix of size 6.

In [4]:
a_i = np.identity(6)
a_i

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# 4. Create an array of 15 evenly spaced values between 10 and 50.

In [5]:
a_lin = np.linspace(10,50,15)
a_lin

array([10.        , 12.85714286, 15.71428571, 18.57142857, 21.42857143,
       24.28571429, 27.14285714, 30.        , 32.85714286, 35.71428571,
       38.57142857, 41.42857143, 44.28571429, 47.14285714, 50.        ])

# 5. Print the shape, size, and dtype of a given array.

In [6]:
a_2d = np.arange(0,25).reshape((5,5))
a_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [7]:
print('Shape of the array ',a_2d.shape)
print('Size of the array ',a_2d.size)
print('Dtype of array, ',a_2d.dtype)

Shape of the array  (5, 5)
Size of the array  25
Dtype of array,  int64


# 6. Convert a nested Python list into a 2D NumPy array.

In [8]:
python_list = [[1,3,4,5,6,7],[3,7,8,5,6,3]]
type(python_list)
python_list


[[1, 3, 4, 5, 6, 7], [3, 7, 8, 5, 6, 3]]

In [9]:
array = np.array(python_list)
type(array)

numpy.ndarray

In [10]:
array.ndim

2

# 7. Create a 3x3 array filled with the value 9.

In [11]:
a_nine = np.full((3,3),9)

# 8. Reshape a 1D array of 20 elements into a 4x5 matrix.

In [12]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [13]:
a_reshape = a.reshape((4,5))
a_reshape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# 9. Change the dtype of an array to float64.

In [14]:
a = np.arange(20).astype(np.float32)
a.dtype

dtype('float32')

In [15]:
a.dtype

dtype('float32')

# 10. Create an array of 10 zeros and then set the 5th element to 100.

In [16]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
a.put(4,100)
a

array([  0.,   0.,   0.,   0., 100.,   0.,   0.,   0.,   0.,   0.])

# 11. Extract every 3rd element from a 1D array.

In [18]:
a = np.arange(20)
print(a[3])

3


# 12. Reverse a 2D array along its rows.

In [19]:
a_2d = np.random.randint(10,100,25).reshape((5,5))
a_2d

array([[82, 31, 47, 89, 72],
       [16, 28, 34, 42, 82],
       [19, 77, 48, 15, 47],
       [63, 68, 94, 55, 89],
       [61, 61, 70, 18, 73]])

In [20]:
np.flip(a_2d,axis=0)

array([[61, 61, 70, 18, 73],
       [63, 68, 94, 55, 89],
       [19, 77, 48, 15, 47],
       [16, 28, 34, 42, 82],
       [82, 31, 47, 89, 72]])

# 13. Extract the last row and last column of a matrix.

In [21]:
a_2d = np.random.randint(10,300,30).reshape((6,5))
a_2d

array([[294,  72, 228, 299,  71],
       [254, 132, 184,  13, 128],
       [170, 115,  12, 192, 264],
       [281,  94, 199, 104,  21],
       [ 50,  18, 110, 196,  53],
       [ 36, 124, 178,  82,  79]])

In [22]:
a_2d[-1,:] #last row
a_2d[:,-1] #last column

array([ 71, 128, 264,  21,  53,  79])

# 14. Get all values from an array that are divisible by 3.

In [23]:
a = np.random.randint(1,2000,40)

In [24]:
a[a%3==0]

array([ 822,  366, 1164,  291,  768, 1101, 1791, 1452,  510,  288])

# 15. Replace all values greater than 50 in an array with 50.

In [25]:
a = np.random.randint(1,70,20)
a

array([13, 37, 10, 59, 53, 61, 54, 36, 61, 47, 37, 31, 62, 49, 34, 45, 59,
       50,  3, 59])

In [26]:
np.where(a>50,50,a)

array([13, 37, 10, 50, 50, 50, 50, 36, 50, 47, 37, 31, 50, 49, 34, 45, 50,
       50,  3, 50])

# 16. Extract a 3x3 sub-matrix from the center of a 6x6 matrix.

In [27]:
a = np.random.randint(10,100,36).reshape((6,6))
a

array([[86, 19, 59, 70, 94, 82],
       [63, 36, 32, 98, 61, 29],
       [41, 63, 14, 49, 43, 95],
       [99, 84, 32, 66, 91, 13],
       [26, 64, 16, 20, 41, 61],
       [53, 50, 35, 73, 89, 94]])

In [28]:
sub_metrix = a[2:5,1:4]
sub_metrix

array([[63, 14, 49],
       [84, 32, 66],
       [64, 16, 20]])

# 17. Find the indices of all elements equal to a given value

In [29]:
a = np.array([1,2,3,5,3,2,6,4,7,4,3,6,7,8,23,6,9,6,4,3,3,5,7,89,67,4,5,6,7])
value = int(input('Enter your number: '))
np.where(a==value)

(array([ 2,  4, 10, 19, 20]),)

# 18. Select rows of a matrix where the value in the first column is even.

In [30]:
a = np.random.randint(10,100,36).reshape((6,6))
a

array([[66, 41, 69, 98, 46, 12],
       [56, 38, 46, 19, 81, 40],
       [87, 21, 56, 46, 95, 53],
       [89, 53, 72, 72, 52, 72],
       [60, 37, 73, 47, 66, 68],
       [61, 51, 52, 11, 82, 52]])

In [31]:
a = a[a[:,0]%2==0]

In [32]:
a

array([[66, 41, 69, 98, 46, 12],
       [56, 38, 46, 19, 81, 40],
       [60, 37, 73, 47, 66, 68]])

# 19. Select rows at index positions 1, 4, and 6 from a matrix

In [33]:
a = np.random.randint(10,100,49).reshape((7,7))
a

array([[51, 41, 42, 49, 54, 35, 57],
       [44, 47, 66, 35, 51, 67, 80],
       [53, 53, 69, 90, 23, 49, 81],
       [25, 30, 58, 25, 70, 80, 16],
       [43, 89, 15, 91, 71, 22, 59],
       [94, 42, 10, 72, 40, 72, 63],
       [75, 94, 42, 72, 45, 26, 35]])

In [34]:
a[[1,4,6]]

array([[44, 47, 66, 35, 51, 67, 80],
       [43, 89, 15, 91, 71, 22, 59],
       [75, 94, 42, 72, 45, 26, 35]])

# 20. Set all values below 0 in an array to 0 and above 100 to 100.

In [35]:
a = np.random.randint(-10,200,49).reshape((7,7))
a

array([[178,  27,  85, 199,  -8,  -2,  -9],
       [ -9,  82,  52, 115,  95,  69, 143],
       [185, 190, 141,  77,  76, 120,  28],
       [ 65, 172,  87,  16, 133, 176, 170],
       [  9,  -2, 142, 166,  62, 178,  91],
       [137,  90,   1, 100,   9, 178,  39],
       [173,  38, 128, 182, 108,  46,  68]])

In [36]:
np.clip(a,0,100)

array([[100,  27,  85, 100,   0,   0,   0],
       [  0,  82,  52, 100,  95,  69, 100],
       [100, 100, 100,  77,  76, 100,  28],
       [ 65, 100,  87,  16, 100, 100, 100],
       [  9,   0, 100, 100,  62, 100,  91],
       [100,  90,   1, 100,   9, 100,  39],
       [100,  38, 100, 100, 100,  46,  68]])

# 21. Flatten a 3D array of shape (2,3,4) into 1D

In [37]:
a = np.arange(0,24).reshape((2,3,4))

In [38]:
flatten_a = a.flatten()

In [39]:
flatten_a[3] = 100

In [40]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [41]:
ravel_a = np.ravel(a) 

In [42]:
ravel_a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [43]:
ravel_a[3] = 100

### Flatten make a new copy so change is flatten array does not effect original array, but ravel just make view so it impact on orginal array.

## 22. Reshape a (60,) array into (3,4,5).

In [44]:
a = np.random.randint(10,1000,(60,))

In [45]:
a = a.reshape(3,4,5)

In [46]:
a.shape

(3, 4, 5)

# 23. Stack two 1D arrays vertically and then horizontally.

In [47]:
a = np.arange(0,20)
b = np.linspace(1,100,20).astype(np.int32)

In [48]:
c = np.stack([a,b],axis=1) #for horizontal
d = np.stack([a,b],axis=0) #for vertical

In [49]:
d

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19],
       [  1,   6,  11,  16,  21,  27,  32,  37,  42,  47,  53,  58,  63,
         68,  73,  79,  84,  89,  94, 100]])

In [50]:
print(a.ndim)
print(c.ndim)

1
2


# 24. Concatenate two 2D arrays row-wise and column-wise.

In [51]:
a = np.arange(24).reshape(6,4)
b = np.random.randint(20,100,24).reshape(6,4).astype(np.int32)

In [52]:
b

array([[96, 47, 52, 56],
       [94, 20, 43, 75],
       [29, 39, 38, 77],
       [36, 83, 82, 72],
       [60, 59, 87, 89],
       [64, 38, 70, 59]], dtype=int32)

In [53]:
c = np.concatenate((a,b),axis=0) #for vertical
d = np.concatenate((a,b),axis=1) #for horizontal

In [54]:
print(a.ndim)
print(c.ndim)

2
2


In [55]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [96, 47, 52, 56],
       [94, 20, 43, 75],
       [29, 39, 38, 77],
       [36, 83, 82, 72],
       [60, 59, 87, 89],
       [64, 38, 70, 59]])

np.concatenate glues arrays together along an existing direction, keeping the total number of dimensions unchanged.

np.stack joins arrays along a brand-new direction, increasing the dimension count by one (e.g., turning 1D inputs into a 2D output).

1D Array Limitation: You cannot concatenate 1D arrays vertically because 1D arrays only have one axis—np.concatenate will simply join them end-to-end into a longer 1D array.

To Combine 1D Vertically: You must use np.stack (or np.vstack), which adds the necessary second dimension to create stacked rows in a 2D matrix.

# 25. Split an array of 20 elements into 4 equal parts.

In [56]:
a = np.arange(20)

In [57]:
a,b,c,d =np.split(a,4)

#  26. Transpose a 3x5 matrix 

In [58]:
a = np.arange(15).reshape(3,5)

In [59]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [60]:
a.T # 1 Way

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [61]:
np.transpose(a) # 2 Way

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

# 27. Convert a 1D array of shape (10,) into shape (10,1).

In [62]:
a = np.random.randint(1,199,10)

In [63]:
a = np.expand_dims(a,axis=1) # method 1

In [64]:
a.shape

(10, 1)

In [65]:
b = a.reshape(10,1) # method 2

In [66]:
b.shape

(10, 1)

# 28. Swap the first and last axis of a 3D array.

In [67]:
a = np.arange(24).reshape(2,3,4) 

In [68]:
a.shape

(2, 3, 4)

In [69]:
b = a.reshape(4,3,2) #method 1
c = np.swapaxes(a,0,2) #method 2
d = np.transpose(a,(2,1,0)) #method 3

In [70]:
d.shape

(4, 3, 2)

There is three method fot this task .. method 2 and 3 is actual answer

# 30. Repeat a 1D array 4 times to build a 2D array.

In [71]:
a = np.arange(5)

In [72]:
a_1 = np.tile(a,(4,1)) #method 1
b = np.broadcast_to(a,(4,len(a))) #method 2
c = np.vstack([a]*4) #method 3
d = np.repeat(a, 4).reshape(-1, 4) #method 4

In [73]:
d.shape

(5, 4)

In [74]:
d

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4]])

# 31. Add a 1D array to each row of a 2D array.

In [83]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [84]:
b = np.arange(10).reshape(2,5)

In [85]:
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [86]:
c = a+b

In [87]:
c

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13]])

# 32. Multiply each column of a matrix by a different value from a 1D array.