In [1]:
import numpy as np

# 1. Create a 1D array of numbers from 0 to 20.


In [2]:
a = np.arange(21)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

# 2. Create a 2D array of shape 4x5 filled with ones.

In [3]:
a_one = np.ones((4,5))
a_one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# 3. Create an identity matrix of size 6.

In [4]:
a_i = np.identity(6)
a_i

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# 4. Create an array of 15 evenly spaced values between 10 and 50.

In [5]:
a_lin = np.linspace(10,50,15)
a_lin

array([10.        , 12.85714286, 15.71428571, 18.57142857, 21.42857143,
       24.28571429, 27.14285714, 30.        , 32.85714286, 35.71428571,
       38.57142857, 41.42857143, 44.28571429, 47.14285714, 50.        ])

# 5. Print the shape, size, and dtype of a given array.

In [6]:
a_2d = np.arange(0,25).reshape((5,5))
a_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [7]:
print('Shape of the array ',a_2d.shape)
print('Size of the array ',a_2d.size)
print('Dtype of array, ',a_2d.dtype)

Shape of the array  (5, 5)
Size of the array  25
Dtype of array,  int64


# 6. Convert a nested Python list into a 2D NumPy array.

In [8]:
python_list = [[1,3,4,5,6,7],[3,7,8,5,6,3]]
type(python_list)
python_list


[[1, 3, 4, 5, 6, 7], [3, 7, 8, 5, 6, 3]]

In [9]:
array = np.array(python_list)
type(array)

numpy.ndarray

In [10]:
array.ndim

2

# 7. Create a 3x3 array filled with the value 9.

In [11]:
a_nine = np.full((3,3),9)

# 8. Reshape a 1D array of 20 elements into a 4x5 matrix.

In [12]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [13]:
a_reshape = a.reshape((4,5))
a_reshape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# 9. Change the dtype of an array to float64.

In [14]:
a = np.arange(20).astype(np.float32)
a.dtype

dtype('float32')

In [15]:
a.dtype

dtype('float32')

# 10. Create an array of 10 zeros and then set the 5th element to 100.

In [16]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
a.put(4,100)
a

array([  0.,   0.,   0.,   0., 100.,   0.,   0.,   0.,   0.,   0.])

# 11. Extract every 3rd element from a 1D array.

In [18]:
a = np.arange(20)
print(a[3])

3


# 12. Reverse a 2D array along its rows.

In [19]:
a_2d = np.random.randint(10,100,25).reshape((5,5))
a_2d

array([[52, 32, 99, 45, 99],
       [46, 89, 91, 45, 99],
       [46, 94, 74, 88, 69],
       [77, 41, 97, 58, 34],
       [51, 56, 60, 77, 89]])

In [20]:
np.flip(a_2d,axis=0)

array([[51, 56, 60, 77, 89],
       [77, 41, 97, 58, 34],
       [46, 94, 74, 88, 69],
       [46, 89, 91, 45, 99],
       [52, 32, 99, 45, 99]])

# 13. Extract the last row and last column of a matrix.

In [21]:
a_2d = np.random.randint(10,300,30).reshape((6,5))
a_2d

array([[ 96,  60, 194, 137,  70],
       [ 33, 282,  95, 291,  10],
       [118, 108, 224, 116, 170],
       [ 48, 243, 139, 203,  91],
       [140, 193, 278, 247, 168],
       [175, 279, 190, 278, 156]])

In [22]:
a_2d[-1,:] #last row
a_2d[:,-1] #last column

array([ 70,  10, 170,  91, 168, 156])

# 14. Get all values from an array that are divisible by 3.

In [23]:
a = np.random.randint(1,2000,40)

In [24]:
a[a%3==0]

array([  87, 1194,  678,  561,   99,  942,  315, 1491, 1146,  165])

# 15. Replace all values greater than 50 in an array with 50.

In [25]:
a = np.random.randint(1,70,20)
a

array([11, 16, 65, 23, 38, 45, 27, 35, 37,  1, 54, 17, 66, 11,  6, 47, 65,
       51, 43, 26])

In [26]:
np.where(a>50,50,a)

array([11, 16, 50, 23, 38, 45, 27, 35, 37,  1, 50, 17, 50, 11,  6, 47, 50,
       50, 43, 26])

# 16. Extract a 3x3 sub-matrix from the center of a 6x6 matrix.

In [27]:
a = np.random.randint(10,100,36).reshape((6,6))
a

array([[80, 70, 97, 73, 89, 62],
       [86, 57, 63, 43, 14, 39],
       [33, 62, 93, 79, 65, 62],
       [43, 28, 74, 63, 31, 10],
       [39, 36, 89, 88, 74, 42],
       [60, 56, 58, 33, 24, 39]])

In [28]:
sub_metrix = a[2:5,1:4]
sub_metrix

array([[62, 93, 79],
       [28, 74, 63],
       [36, 89, 88]])

# 17. Find the indices of all elements equal to a given value

In [29]:
a = np.array([1,2,3,5,3,2,6,4,7,4,3,6,7,8,23,6,9,6,4,3,3,5,7,89,67,4,5,6,7])
value = int(input('Enter your number: '))
np.where(a==value)

(array([1, 5]),)

# 18. Select rows of a matrix where the value in the first column is even.

In [30]:
a = np.random.randint(10,100,36).reshape((6,6))
a

array([[83, 20, 94, 38, 18, 35],
       [96, 20, 44, 11, 69, 93],
       [34, 39, 55, 32, 32, 46],
       [64, 17, 26, 11, 97, 52],
       [32, 77, 40, 56, 25, 92],
       [46, 45, 91, 67, 68, 25]])

In [31]:
a = a[a[:,0]%2==0]

In [32]:
a

array([[96, 20, 44, 11, 69, 93],
       [34, 39, 55, 32, 32, 46],
       [64, 17, 26, 11, 97, 52],
       [32, 77, 40, 56, 25, 92],
       [46, 45, 91, 67, 68, 25]])

# 19. Select rows at index positions 1, 4, and 6 from a matrix

In [33]:
a = np.random.randint(10,100,49).reshape((7,7))
a

array([[51, 26, 99, 35, 99, 26, 53],
       [49, 15, 31, 44, 71, 37, 40],
       [63, 52, 40, 90, 62, 97, 88],
       [48, 50, 99, 14, 50, 64, 41],
       [99, 39, 98, 34, 63, 77, 94],
       [31, 41, 74, 51, 29, 12, 15],
       [26, 40, 16, 75, 46, 33, 90]])

In [34]:
a[[1,4,6]]

array([[49, 15, 31, 44, 71, 37, 40],
       [99, 39, 98, 34, 63, 77, 94],
       [26, 40, 16, 75, 46, 33, 90]])

# 20. Set all values below 0 in an array to 0 and above 100 to 100.

In [35]:
a = np.random.randint(-10,200,49).reshape((7,7))
a

array([[  2,  54, 176,  14,  50, 151, 103],
       [138, 187,  -2,  43,  56, 153, 185],
       [ 67, 133,  44, 130,  34, 169,  28],
       [ 88,  57,  82,  50, 198, 170, 101],
       [ -6,   8, 140, 153,  17, 184,   1],
       [ 39,  26, 100,   8,  38, 161,   0],
       [120, 192, 131,  63, 153, 165, 180]])

In [36]:
np.clip(a,0,100)

array([[  2,  54, 100,  14,  50, 100, 100],
       [100, 100,   0,  43,  56, 100, 100],
       [ 67, 100,  44, 100,  34, 100,  28],
       [ 88,  57,  82,  50, 100, 100, 100],
       [  0,   8, 100, 100,  17, 100,   1],
       [ 39,  26, 100,   8,  38, 100,   0],
       [100, 100, 100,  63, 100, 100, 100]])

# 21. Flatten a 3D array of shape (2,3,4) into 1D

In [44]:
a = np.arange(0,24).reshape((2,3,4))

In [46]:
flatten_a = a.flatten()

In [48]:
flatten_a[3] = 100

In [50]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [51]:
ravel_a = np.ravel(a) 

In [52]:
ravel_a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [53]:
ravel_a[3] = 100

### Flatten make a new copy so change is flatten array does not effect original array, but ravel just make view so it impact on orginal array.

## 22. Reshape a (60,) array into (3,4,5).

In [63]:
a = np.random.randint(10,1000,(60,))

In [67]:
a = a.reshape(3,4,5)

In [69]:
a.shape

(3, 4, 5)

# 23. Stack two 1D arrays vertically and then horizontally.

In [115]:
a = np.arange(0,20)
b = np.linspace(1,100,20).astype(np.int32)

In [116]:
c = np.stack([a,b],axis=1) #for horizontal
d = np.stack([a,b],axis=0) #for vertical

In [117]:
d

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19],
       [  1,   6,  11,  16,  21,  27,  32,  37,  42,  47,  53,  58,  63,
         68,  73,  79,  84,  89,  94, 100]])

In [118]:
print(a.ndim)
print(c.ndim)

1
2


# 24. Concatenate two 2D arrays row-wise and column-wise.

In [133]:
a = np.arange(24).reshape(6,4)
b = np.random.randint(20,100,24).reshape(6,4).astype(np.int32)

In [134]:
b

array([[40, 40, 58, 62],
       [72, 46, 31, 64],
       [90, 66, 58, 65],
       [56, 65, 36, 49],
       [71, 25, 53, 23],
       [99, 80, 97, 64]], dtype=int32)

In [135]:
c = np.concatenate((a,b),axis=0) #for vertical
d = np.concatenate((a,b),axis=1) #for horizontal

In [124]:
print(a.ndim)
print(c.ndim)

2
2


In [129]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [87, 53, 81, 72],
       [99, 68, 26, 81],
       [95, 46, 80, 60],
       [71, 36, 83, 37],
       [64, 32, 34, 88],
       [80, 33, 73, 65]])

np.concatenate glues arrays together along an existing direction, keeping the total number of dimensions unchanged.

np.stack joins arrays along a brand-new direction, increasing the dimension count by one (e.g., turning 1D inputs into a 2D output).

1D Array Limitation: You cannot concatenate 1D arrays vertically because 1D arrays only have one axis—np.concatenate will simply join them end-to-end into a longer 1D array.

To Combine 1D Vertically: You must use np.stack (or np.vstack), which adds the necessary second dimension to create stacked rows in a 2D matrix.