In [1]:
import numpy as np

# 1. Create a 1D array of numbers from 0 to 20.


In [2]:
a = np.arange(21)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

# 2. Create a 2D array of shape 4x5 filled with ones.

In [3]:
a_one = np.ones((4,5))
a_one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# 3. Create an identity matrix of size 6.

In [4]:
a_i = np.identity(6)
a_i

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# 4. Create an array of 15 evenly spaced values between 10 and 50.

In [5]:
a_lin = np.linspace(10,50,15)
a_lin

array([10.        , 12.85714286, 15.71428571, 18.57142857, 21.42857143,
       24.28571429, 27.14285714, 30.        , 32.85714286, 35.71428571,
       38.57142857, 41.42857143, 44.28571429, 47.14285714, 50.        ])

# 5. Print the shape, size, and dtype of a given array.

In [6]:
a_2d = np.arange(0,25).reshape((5,5))
a_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [7]:
print('Shape of the array ',a_2d.shape)
print('Size of the array ',a_2d.size)
print('Dtype of array, ',a_2d.dtype)

Shape of the array  (5, 5)
Size of the array  25
Dtype of array,  int64


# 6. Convert a nested Python list into a 2D NumPy array.

In [8]:
python_list = [[1,3,4,5,6,7],[3,7,8,5,6,3]]
type(python_list)
python_list


[[1, 3, 4, 5, 6, 7], [3, 7, 8, 5, 6, 3]]

In [9]:
array = np.array(python_list)
type(array)

numpy.ndarray

In [10]:
array.ndim

2

# 7. Create a 3x3 array filled with the value 9.

In [11]:
a_nine = np.full((3,3),9)

# 8. Reshape a 1D array of 20 elements into a 4x5 matrix.

In [12]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [13]:
a_reshape = a.reshape((4,5))
a_reshape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# 9. Change the dtype of an array to float64.

In [14]:
a = np.arange(20).astype(np.float32)
a.dtype

dtype('float32')

In [15]:
a.dtype

dtype('float32')

# 10. Create an array of 10 zeros and then set the 5th element to 100.

In [16]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
a.put(4,100)
a

array([  0.,   0.,   0.,   0., 100.,   0.,   0.,   0.,   0.,   0.])

# 11. Extract every 3rd element from a 1D array.

In [18]:
a = np.arange(20)
print(a[3])

3


# 12. Reverse a 2D array along its rows.

In [19]:
a_2d = np.random.randint(10,100,25).reshape((5,5))
a_2d

array([[12, 36, 46, 31, 79],
       [94, 19, 29, 88, 48],
       [27, 31, 22, 47, 11],
       [25, 95, 58, 27, 57],
       [31, 97, 14, 56, 35]])

In [20]:
np.flip(a_2d,axis=0)

array([[31, 97, 14, 56, 35],
       [25, 95, 58, 27, 57],
       [27, 31, 22, 47, 11],
       [94, 19, 29, 88, 48],
       [12, 36, 46, 31, 79]])

# 13. Extract the last row and last column of a matrix.

In [21]:
a_2d = np.random.randint(10,300,30).reshape((6,5))
a_2d

array([[ 55,  34, 210, 170,  52],
       [269, 111, 247, 131, 182],
       [ 81,  80, 275, 273, 280],
       [233, 134, 217, 198,  70],
       [ 59,  81, 257,  60,  69],
       [ 94,  24, 166, 267, 138]])

In [22]:
a_2d[-1,:] #last row
a_2d[:,-1] #last column

array([ 52, 182, 280,  70,  69, 138])

# 14. Get all values from an array that are divisible by 3.

In [23]:
a = np.random.randint(1,2000,40)

In [24]:
a[a%3==0]

array([1665, 1770, 1179,  834,  582, 1344,  252,  783, 1116,  333,  738,
        222,  840])

# 15. Replace all values greater than 50 in an array with 50.

In [25]:
a = np.random.randint(1,70,20)
a

array([64, 39, 14,  2, 51, 41, 52, 49, 56, 24, 32,  5, 58, 16, 18, 19, 22,
       35, 11, 52])

In [26]:
np.where(a>50,50,a)

array([50, 39, 14,  2, 50, 41, 50, 49, 50, 24, 32,  5, 50, 16, 18, 19, 22,
       35, 11, 50])

# 16. Extract a 3x3 sub-matrix from the center of a 6x6 matrix.

In [27]:
a = np.random.randint(10,100,36).reshape((6,6))
a

array([[63, 34, 91, 74, 79, 82],
       [21, 52, 90, 61, 56, 60],
       [33, 18, 38, 58, 13, 26],
       [66, 67, 91, 60, 76, 84],
       [59, 52, 20, 97, 79, 87],
       [45, 93, 66, 44, 58, 99]])

In [28]:
sub_metrix = a[2:5,1:4]
sub_metrix

array([[18, 38, 58],
       [67, 91, 60],
       [52, 20, 97]])

# 17. Find the indices of all elements equal to a given value

In [29]:
a = np.array([1,2,3,5,3,2,6,4,7,4,3,6,7,8,23,6,9,6,4,3,3,5,7,89,67,4,5,6,7])
value = int(input('Enter your number: '))
np.where(a==value)

(array([], dtype=int64),)

# 18. Select rows of a matrix where the value in the first column is even.

In [30]:
a = np.random.randint(10,100,36).reshape((6,6))
a

array([[31, 81, 24, 83, 88, 87],
       [20, 13, 22, 21, 97, 66],
       [92, 34, 82, 84, 65, 82],
       [95, 83, 66, 17, 69, 65],
       [86, 67, 90, 21, 28, 98],
       [96, 93, 64, 67, 14, 26]])

In [31]:
a = a[a[:,0]%2==0]

In [32]:
a

array([[20, 13, 22, 21, 97, 66],
       [92, 34, 82, 84, 65, 82],
       [86, 67, 90, 21, 28, 98],
       [96, 93, 64, 67, 14, 26]])

# 19. Select rows at index positions 1, 4, and 6 from a matrix

In [33]:
a = np.random.randint(10,100,49).reshape((7,7))
a

array([[21, 92, 59, 31, 16, 20, 77],
       [16, 71, 39, 32, 15, 61, 73],
       [37, 60, 30, 28, 97, 50, 83],
       [43, 81, 23, 41, 38, 66, 79],
       [87, 67, 38, 51, 62, 49, 40],
       [59, 58, 85, 12, 29, 52, 96],
       [95, 84, 16, 18, 21, 25, 22]])

In [34]:
a[[1,4,6]]

array([[16, 71, 39, 32, 15, 61, 73],
       [87, 67, 38, 51, 62, 49, 40],
       [95, 84, 16, 18, 21, 25, 22]])

# 20. Set all values below 0 in an array to 0 and above 100 to 100.

In [35]:
a = np.random.randint(-10,200,49).reshape((7,7))
a

array([[162, 131,  64, 175, 128,  85,   1],
       [138, 157,  20, 188, 171,  33, 155],
       [121, 135,  47, 135,   2,  80,  83],
       [138, 176, 146, 155,  74,  89,  57],
       [ 73, -10, 127, 111,  91, 180, 185],
       [140,  77,  43,  82, 111, 137,  24],
       [ 47, 140, 154,   8, 199,  20, 141]])

In [36]:
np.clip(a,0,100)

array([[100, 100,  64, 100, 100,  85,   1],
       [100, 100,  20, 100, 100,  33, 100],
       [100, 100,  47, 100,   2,  80,  83],
       [100, 100, 100, 100,  74,  89,  57],
       [ 73,   0, 100, 100,  91, 100, 100],
       [100,  77,  43,  82, 100, 100,  24],
       [ 47, 100, 100,   8, 100,  20, 100]])

# 21. Flatten a 3D array of shape (2,3,4) into 1D

In [37]:
a = np.arange(0,24).reshape((2,3,4))

In [38]:
flatten_a = a.flatten()

In [39]:
flatten_a[3] = 100

In [40]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [41]:
ravel_a = np.ravel(a) 

In [42]:
ravel_a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [43]:
ravel_a[3] = 100

### Flatten make a new copy so change is flatten array does not effect original array, but ravel just make view so it impact on orginal array.

## 22. Reshape a (60,) array into (3,4,5).

In [44]:
a = np.random.randint(10,1000,(60,))

In [45]:
a = a.reshape(3,4,5)

In [46]:
a.shape

(3, 4, 5)

# 23. Stack two 1D arrays vertically and then horizontally.

In [47]:
a = np.arange(0,20)
b = np.linspace(1,100,20).astype(np.int32)

In [48]:
c = np.stack([a,b],axis=1) #for horizontal
d = np.stack([a,b],axis=0) #for vertical

In [49]:
d

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19],
       [  1,   6,  11,  16,  21,  27,  32,  37,  42,  47,  53,  58,  63,
         68,  73,  79,  84,  89,  94, 100]])

In [50]:
print(a.ndim)
print(c.ndim)

1
2


# 24. Concatenate two 2D arrays row-wise and column-wise.

In [51]:
a = np.arange(24).reshape(6,4)
b = np.random.randint(20,100,24).reshape(6,4).astype(np.int32)

In [52]:
b

array([[89, 72, 51, 99],
       [55, 84, 65, 29],
       [25, 28, 77, 69],
       [26, 34, 87, 93],
       [64, 35, 86, 29],
       [22, 36, 47, 29]], dtype=int32)

In [53]:
c = np.concatenate((a,b),axis=0) #for vertical
d = np.concatenate((a,b),axis=1) #for horizontal

In [54]:
print(a.ndim)
print(c.ndim)

2
2


In [55]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [89, 72, 51, 99],
       [55, 84, 65, 29],
       [25, 28, 77, 69],
       [26, 34, 87, 93],
       [64, 35, 86, 29],
       [22, 36, 47, 29]])

np.concatenate glues arrays together along an existing direction, keeping the total number of dimensions unchanged.

np.stack joins arrays along a brand-new direction, increasing the dimension count by one (e.g., turning 1D inputs into a 2D output).

1D Array Limitation: You cannot concatenate 1D arrays vertically because 1D arrays only have one axis—np.concatenate will simply join them end-to-end into a longer 1D array.

To Combine 1D Vertically: You must use np.stack (or np.vstack), which adds the necessary second dimension to create stacked rows in a 2D matrix.

# 25. Split an array of 20 elements into 4 equal parts.

In [56]:
a = np.arange(20)

In [57]:
a,b,c,d =np.split(a,4)

#  26. Transpose a 3x5 matrix 

In [58]:
a = np.arange(15).reshape(3,5)

In [59]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [60]:
a.T # 1 Way

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [61]:
np.transpose(a) # 2 Way

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

# 27. Convert a 1D array of shape (10,) into shape (10,1).

In [62]:
a = np.random.randint(1,199,10)

In [63]:
a = np.expand_dims(a,axis=1) # method 1

In [64]:
a.shape

(10, 1)

In [65]:
b = a.reshape(10,1) # method 2

In [66]:
b.shape

(10, 1)

# 28. Swap the first and last axis of a 3D array.

In [ ]:
a = np.arange(24).reshape(2,3,4) 

In [69]:
a.shape

(2, 3, 4)

In [79]:
b = a.reshape(4,3,2) #method 1
c = np.swapaxes(a,0,2) #method 2
d = np.transpose(a,(2,1,0)) #method 3

In [78]:
d.shape

(4, 3, 2)

There is three method fot this task .. method 2 and 3 is actual answer

# 30. Repeat a 1D array 4 times to build a 2D array.

In [108]:
a = np.arange(5)

In [130]:
a_1 = np.tile(a,(4,1)) #method 1
b = np.broadcast_to(a,(4,len(a))) #method 2
c = np.vstack([a]*4) #method 3
d = np.repeat(a, 4).reshape(-1, 4) #method 4

In [128]:
d.shape

(5, 4)

In [129]:
d

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4]])

# 31. Add a 1D array to each row of a 2D array.